# Build matrix
language: node_js
matrix:
  include:

    # Run linter once
    - node_js: '10'
      env: LINT=true

    # Run tests
    - node_js: '10'
    - node_js: '12'
    - node_js: '14'

# Build script
script:
  - 'if [ $LINT ]; then npm run lint; fi'
  - 'if [ ! $LINT ]; then npm test; fi'
