
# Language/versions
language: node_js
node_js:
  - "0.12"
  - "0.10"

# Build only master (and pull-requests)
branches:
  only:
    - master

# Build script
script: make ci

# Notifications
notifications:
  email:
    - j.robinson@nature.com
    - rowan.manning@nature.com
  slack: thefeds:vG3hLYB07EwTYpQFp3TNUx82
