# This workflow will do a clean install of node dependencies, build the source code and run tests.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pa11y build tests

on:
  push:
    branches: [ master, github-actions ] # Run actions when code is committed to these branches
  pull_request:
    branches: [ master ] # Run actions when a PR is pushed based on these branches

jobs:
  checkout_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - node-version: 10.x
           env:
            LINT: true
         - node-version: 12.x
         - node-version: 14.x

    steps:
      - name: Checkout code from ${{ github.repository }}
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
        shell: bash
      - name: Try to run with Linter
        run: 'if [ $LINT ]; then npm run lint; fi'
        shell: bash
        env:
          LINT: ${{env.lint}}
      - name: Try to run without Linter
        run: 'if [ ! $LINT ]; then npm test; fi'
        shell: bash
